// Code generated by MockGen. DO NOT EDIT.
// Source: port/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "github.com/Kenji-Uema/cottageManager/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/v2/bson/primitive"
)

// MockBookingRepo is a mock of BookingRepo interface.
type MockBookingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepoMockRecorder
}

// MockBookingRepoMockRecorder is the mock recorder for MockBookingRepo.
type MockBookingRepoMockRecorder struct {
	mock *MockBookingRepo
}

// NewMockBookingRepo creates a new mock instance.
func NewMockBookingRepo(ctrl *gomock.Controller) *MockBookingRepo {
	mock := &MockBookingRepo{ctrl: ctrl}
	mock.recorder = &MockBookingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepo) EXPECT() *MockBookingRepoMockRecorder {
	return m.recorder
}

// AddBooking mocks base method.
func (m *MockBookingRepo) AddBooking(ctx context.Context, booking domain.Booking) (primitive.ObjectID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBooking", ctx, booking)
	ret0, _ := ret[0].(primitive.ObjectID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBooking indicates an expected call of AddBooking.
func (mr *MockBookingRepoMockRecorder) AddBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBooking", reflect.TypeOf((*MockBookingRepo)(nil).AddBooking), ctx, booking)
}

// DeleteBooking mocks base method.
func (m *MockBookingRepo) DeleteBooking(ctx context.Context, id primitive.ObjectID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooking", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBooking indicates an expected call of DeleteBooking.
func (mr *MockBookingRepoMockRecorder) DeleteBooking(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooking", reflect.TypeOf((*MockBookingRepo)(nil).DeleteBooking), ctx, id)
}

// GetBookings mocks base method.
func (m *MockBookingRepo) GetBookings(ctx context.Context, ids []primitive.ObjectID) ([]domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookings", ctx, ids)
	ret0, _ := ret[0].([]domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookings indicates an expected call of GetBookings.
func (mr *MockBookingRepoMockRecorder) GetBookings(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookings", reflect.TypeOf((*MockBookingRepo)(nil).GetBookings), ctx, ids)
}

// MockCottageRepo is a mock of CottageRepo interface.
type MockCottageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCottageRepoMockRecorder
}

// MockCottageRepoMockRecorder is the mock recorder for MockCottageRepo.
type MockCottageRepoMockRecorder struct {
	mock *MockCottageRepo
}

// NewMockCottageRepo creates a new mock instance.
func NewMockCottageRepo(ctrl *gomock.Controller) *MockCottageRepo {
	mock := &MockCottageRepo{ctrl: ctrl}
	mock.recorder = &MockCottageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCottageRepo) EXPECT() *MockCottageRepoMockRecorder {
	return m.recorder
}

// AddBooking mocks base method.
func (m *MockCottageRepo) AddBooking(ctx context.Context, name string, bookingId primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBooking", ctx, name, bookingId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBooking indicates an expected call of AddBooking.
func (mr *MockCottageRepoMockRecorder) AddBooking(ctx, name, bookingId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBooking", reflect.TypeOf((*MockCottageRepo)(nil).AddBooking), ctx, name, bookingId)
}

// DeleteBooking mocks base method.
func (m *MockCottageRepo) DeleteBooking(ctx context.Context, name string, bookingId primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooking", ctx, name, bookingId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBooking indicates an expected call of DeleteBooking.
func (mr *MockCottageRepoMockRecorder) DeleteBooking(ctx, name, bookingId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooking", reflect.TypeOf((*MockCottageRepo)(nil).DeleteBooking), ctx, name, bookingId)
}

// GetAll mocks base method.
func (m *MockCottageRepo) GetAll(ctx context.Context) ([]domain.Cottage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]domain.Cottage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCottageRepoMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCottageRepo)(nil).GetAll), ctx)
}

// GetBookingsId mocks base method.
func (m *MockCottageRepo) GetBookingsId(ctx context.Context, name string) ([]primitive.ObjectID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsId", ctx, name)
	ret0, _ := ret[0].([]primitive.ObjectID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsId indicates an expected call of GetBookingsId.
func (mr *MockCottageRepoMockRecorder) GetBookingsId(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsId", reflect.TypeOf((*MockCottageRepo)(nil).GetBookingsId), ctx, name)
}

// GetByName mocks base method.
func (m *MockCottageRepo) GetByName(ctx context.Context, name string) (domain.Cottage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(domain.Cottage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockCottageRepoMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockCottageRepo)(nil).GetByName), ctx, name)
}

// GetByType mocks base method.
func (m *MockCottageRepo) GetByType(ctx context.Context, cottageType string) ([]domain.Cottage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByType", ctx, cottageType)
	ret0, _ := ret[0].([]domain.Cottage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByType indicates an expected call of GetByType.
func (mr *MockCottageRepoMockRecorder) GetByType(ctx, cottageType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByType", reflect.TypeOf((*MockCottageRepo)(nil).GetByType), ctx, cottageType)
}
