// Code generated by MockGen. DO NOT EDIT.
// Source: app/availability_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"cottageManager/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAvailabilityService is a mock of AvailabilityService interface.
type MockAvailabilityService struct {
	ctrl     *gomock.Controller
	recorder *MockAvailabilityServiceMockRecorder
}

// MockAvailabilityServiceMockRecorder is the mock recorder for MockAvailabilityService.
type MockAvailabilityServiceMockRecorder struct {
	mock *MockAvailabilityService
}

// NewMockAvailabilityService creates a new mock instance.
func NewMockAvailabilityService(ctrl *gomock.Controller) *MockAvailabilityService {
	mock := &MockAvailabilityService{ctrl: ctrl}
	mock.recorder = &MockAvailabilityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvailabilityService) EXPECT() *MockAvailabilityServiceMockRecorder {
	return m.recorder
}

// GetAvailablePeriods mocks base method.
func (m *MockAvailabilityService) GetAvailablePeriods(ctx context.Context, name string, period domain.Period) ([]domain.Period, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailablePeriods", ctx, name, period)
	ret0, _ := ret[0].([]domain.Period)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailablePeriods indicates an expected call of GetAvailablePeriods.
func (mr *MockAvailabilityServiceMockRecorder) GetAvailablePeriods(ctx, name, period interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailablePeriods", reflect.TypeOf((*MockAvailabilityService)(nil).GetAvailablePeriods), ctx, name, period)
}

// GetAvailablePeriodsByCottageType mocks base method.
func (m *MockAvailabilityService) GetAvailablePeriodsByCottageType(ctx context.Context, cottageType string, period domain.Period) ([]domain.CottageAvailablePeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailablePeriodsByCottageType", ctx, cottageType, period)
	ret0, _ := ret[0].([]domain.CottageAvailablePeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailablePeriodsByCottageType indicates an expected call of GetAvailablePeriodsByCottageType.
func (mr *MockAvailabilityServiceMockRecorder) GetAvailablePeriodsByCottageType(ctx, cottageType, period interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailablePeriodsByCottageType", reflect.TypeOf((*MockAvailabilityService)(nil).GetAvailablePeriodsByCottageType), ctx, cottageType, period)
}

// IsCottageAvailable mocks base method.
func (m *MockAvailabilityService) IsCottageAvailable(ctx context.Context, cottageName string, period domain.Period) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCottageAvailable", ctx, cottageName, period)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCottageAvailable indicates an expected call of IsCottageAvailable.
func (mr *MockAvailabilityServiceMockRecorder) IsCottageAvailable(ctx, cottageName, period interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCottageAvailable", reflect.TypeOf((*MockAvailabilityService)(nil).IsCottageAvailable), ctx, cottageName, period)
}
