// Code generated by MockGen. DO NOT EDIT.
// Source: app/booking_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"cottageManager/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockBookingService is a mock of BookingService interface.
type MockBookingService struct {
	ctrl     *gomock.Controller
	recorder *MockBookingServiceMockRecorder
}

// MockBookingServiceMockRecorder is the mock recorder for MockBookingService.
type MockBookingServiceMockRecorder struct {
	mock *MockBookingService
}

// NewMockBookingService creates a new mock instance.
func NewMockBookingService(ctrl *gomock.Controller) *MockBookingService {
	mock := &MockBookingService{ctrl: ctrl}
	mock.recorder = &MockBookingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingService) EXPECT() *MockBookingServiceMockRecorder {
	return m.recorder
}

// AddBooking mocks base method.
func (m *MockBookingService) AddBooking(ctx context.Context, booking domain.Booking) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBooking", ctx, booking)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBooking indicates an expected call of AddBooking.
func (mr *MockBookingServiceMockRecorder) AddBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBooking", reflect.TypeOf((*MockBookingService)(nil).AddBooking), ctx, booking)
}

// RemoveBooking mocks base method.
func (m *MockBookingService) RemoveBooking(ctx context.Context, cottageName string, bookingId primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBooking", ctx, cottageName, bookingId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBooking indicates an expected call of RemoveBooking.
func (mr *MockBookingServiceMockRecorder) RemoveBooking(ctx, cottageName, bookingId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBooking", reflect.TypeOf((*MockBookingService)(nil).RemoveBooking), ctx, cottageName, bookingId)
}
