// Code generated by MockGen. DO NOT EDIT.
// Source: app/cottage_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"github.com/Kenji-Uema/cottageManager/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockCottageService is a mock of CottageService interface.
type MockCottageService struct {
	ctrl     *gomock.Controller
	recorder *MockCottageServiceMockRecorder
}

// MockCottageServiceMockRecorder is the mock recorder for MockCottageService.
type MockCottageServiceMockRecorder struct {
	mock *MockCottageService
}

// NewMockCottageService creates a new mock instance.
func NewMockCottageService(ctrl *gomock.Controller) *MockCottageService {
	mock := &MockCottageService{ctrl: ctrl}
	mock.recorder = &MockCottageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCottageService) EXPECT() *MockCottageServiceMockRecorder {
	return m.recorder
}

// AddBooking mocks base method.
func (m *MockCottageService) AddBooking(ctx context.Context, name string, bookingId primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBooking", ctx, name, bookingId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBooking indicates an expected call of AddBooking.
func (mr *MockCottageServiceMockRecorder) AddBooking(ctx, name, bookingId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBooking", reflect.TypeOf((*MockCottageService)(nil).AddBooking), ctx, name, bookingId)
}

// GetAll mocks base method.
func (m *MockCottageService) GetAll(ctx context.Context) ([]domain.Cottage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]domain.Cottage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCottageServiceMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCottageService)(nil).GetAll), ctx)
}

// GetByName mocks base method.
func (m *MockCottageService) GetByName(ctx context.Context, cottageName string) (domain.Cottage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, cottageName)
	ret0, _ := ret[0].(domain.Cottage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockCottageServiceMockRecorder) GetByName(ctx, cottageName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockCottageService)(nil).GetByName), ctx, cottageName)
}

// RemoveBooking mocks base method.
func (m *MockCottageService) RemoveBooking(ctx context.Context, name string, bookingId primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBooking", ctx, name, bookingId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBooking indicates an expected call of RemoveBooking.
func (mr *MockCottageServiceMockRecorder) RemoveBooking(ctx, name, bookingId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBooking", reflect.TypeOf((*MockCottageService)(nil).RemoveBooking), ctx, name, bookingId)
}
